version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-action-deps:
        applies-to: "version-updates"
        patterns: ["*"]
