name: CI
on:
  create: # when tags are created
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build Project
      run: dotnet build -c Release --no-restore src

    - name: Build Packages
      run: dotnet pack src/ImGui.NET -c Release --no-restore --no-build
    - name: List Packages
      run: ls -l bin\Release\ImGui.NET\

    - name: Publish to nuget.org
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push bin\Release\ImGui.NET\*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}
